GET http://localhost:8080/pet/findByStatus
Content-Type: application/json

###

GET http://localhost:8080/pet/findById{petId}
Content-Type: application/json

###

POST http://localhost:8080/pet

Content-type: application/json
{
  "id": 0,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "doggie",
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}

###

